coffe/urls.py
from django.urls import path
from .views import *

app_name = "coffe"

urlpatterns = [
    # path('homepage/', ViewHomepage.as_view(), name='home'),
    path('categories/', CategoryListView.as_view(), name="categories_list"),
    path('item/list/', ItemListView.as_view(), name="list_item"),
    path("item/create/", ItemCreateView.as_view(), name="create_item"),
    path("item/<int:pk>/update/", ItemUpdateView.as_view(), name="update_item"),
    path("item/<int:pk>/delete/", ItemDeleteView.as_view(), name="delete_item"),
    path("user/signup/", CustomerSignupView.as_view(), name="signup_user"),
    path("user/login/", MyLoginView.as_view(), name='login'),
    path('user/logout', MyLogoutView.as_view(), name='logout'),
    path('add_to_cart/', AddToCartView.as_view(), name='add_to_cart'),
    path('remove_from_cart/', RemoveFromCartView.as_view(), name='remove_from_cart'),
    path('', show_home.as_view(), name='home'),
    path('order/list/', OrderListView.as_view(), name='order_list'),
    path('shopingCart/', ViewShoppingCart.as_view(), name='shopping_cart'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path("coffe/", include("coffe.urls")),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

coffe/models.py
from django.contrib.auth.models import AbstractUser, BaseUserManager, UserManager
from django.db import models
from django.contrib.auth.hashers import make_password
from django.apps import apps
from django.utils.html import mark_safe


# Create your models here.

class CustomUserManager(BaseUserManager):
    def _create_user(self, username, phone=None, email=None, password=None, **extra_fields):
        """
        Create and save a user with the given username, email, and password.
        """
        if not username:
            raise ValueError("The given username must be set")
        email = self.normalize_email(email)
        # Lookup the real model class from the global app registry so this
        # manager method can be used in migrations. This is fine because
        # managers are by definition working on the real model.
        GlobalUserModel = apps.get_model(
            self.model._meta.app_label, self.model._meta.object_name
        )
        username = GlobalUserModel.normalize_username(username)
        user = self.model(username=username, phone=phone, email=email, **extra_fields)
        user.password = make_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, username, phone=None, email=None, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", False)
        extra_fields.setdefault("is_superuser", False)
        return self._create_user(username, phone, email, password, **extra_fields)

    def create_superuser(self, username, phone=None, email=None, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)

        if extra_fields.get("is_staff") is not True:
            raise ValueError("Superuser must have is_staff=True.")
        if extra_fields.get("is_superuser") is not True:
            raise ValueError("Superuser must have is_superuser=True.")

        return self._create_user(username, phone, email, password, **extra_fields)


class MyUser(AbstractUser):
    differentـgender = [
        ("F", "زن"),
        ("M", "مرد"),
        ("o", "متفرقه"),
    ]
    roles = [("A", "Accountant"), ("B", "Barista"), ("C", "Cashier"), ("S", " Server")]
    role = models.CharField(max_length=1, choices=roles)
    phone = models.CharField(max_length=12, null=True)
    gender = models.CharField(max_length=1, choices=differentـgender)
    address = models.TextField()
    password = models.CharField(blank=False, null=False, max_length=50)
    is_manager = models.BooleanField(default=False)
    is_customer = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    objects = CustomUserManager()

    def __str__(self):
        return f'{self.username}'

def get_default_image():
    return "images/default/default.jpeg"

class Category(models.Model):
    name = models.CharField(max_length=100)
    image = models.ImageField(verbose_name='CategoryImage', upload_to='images/user_uploads', null=True, blank=True,
                              default=get_default_image)


    def __str__(self):
        return f'{self.name}'

class Item(models.Model):
    category = models.ForeignKey(
        Category, on_delete=models.CASCADE, related_name="items")
    name = models.CharField(max_length=100)
    price = models.FloatField()

    image = models.ImageField(verbose_name='ItemImage', upload_to='images/user_uploads', null=True, blank=True, default=get_default_image)

    def __str__(self):
        return f'{self.name}'
    def image_preview(self):
         return mark_safe('<img src="/../../media/%s" width="150" height="150" />' % (self.image))
    @property
    def thumbnail_preview(self):
        if self.image:
            return mark_safe('<img src= "{}" width="200" height="200" />' .format(self.image.url))


class CustomerOrder(models.Model):
    user = models.ForeignKey(
        MyUser, on_delete=models.CASCADE, related_name='customer_orders')
    item = models.ManyToManyField(
        Item, related_name="customer_orders")
    item_quantity = models.IntegerField()
    total_amount = models.FloatField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.user}'


class SellRecord(models.Model):
    order = models.ForeignKey(
        CustomerOrder, on_delete=models.CASCADE, related_name="sell_records")
    user = models.ForeignKey(
        MyUser, on_delete=models.CASCADE, related_name="sell_records")
    date = models.DateField()

    def __str__(self):
        return f'{self.date}'


class Comment(models.Model):
    item = models.ForeignKey(Item, on_delete=models.CASCADE, related_name="comments")
    user = models.ForeignKey(MyUser, on_delete=models.CASCADE, related_name="comments")
    content = models.TextField()
    level_rate = (
        (5, 'عالی'),
        (4, 'خیلی خوب'),
        (3, 'خوب'),
        (2, 'متوسط'),
        (1, 'افتضاح...')
    )

    rate = models.IntegerField(default=3, choices=level_rate)

    def __str__(self):
        return f'{self.user}'

coffe/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.forms import ModelForm
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import AuthenticationForm
from django.views import View

from .models import MyUser
from django import forms


class CustomerCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = MyUser
        fields = ['phone', ]


class CustomerCreationModelForm(ModelForm):
    class Meta:
        model = MyUser
        fields = ['first_name', 'last_name', 'gender', 'email', 'phone', 'username', 'password', 'address']


class LoginUser(View):
    template_name = 'login.html'
    error_message = forms.CharField(widget=forms.HiddenInput(), required=False)

coffe/views.py
import json
from django.contrib import messages
from django.shortcuts import render, get_object_or_404
from django.views import View
from django.views.generic import ListView, CreateView, DeleteView, DetailView, UpdateView
from .models import Category, Comment, CustomerOrder, Item, SellRecord, MyUser
from django.urls import reverse_lazy
from .forms import CustomerCreationModelForm
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import AuthenticationForm


# Create your views here.


class CustomerSignupView(CreateView):
    model = MyUser
    template_name = 'coffe/customer_create.html'
    form_class = CustomerCreationModelForm
    success_url = reverse_lazy('coffe:login')

    # def form_valid(self, form):
    #     form.instance.is_customer = self.request.user
    #     return super().form_valid(form)


class MyLoginView(LoginView):
    template_name = 'coffe/login.html'
    success_url = reverse_lazy('coffe:home')  # Change in the future

    def get_success_url(self):
        # چک کردن مسیر موفقیت‌آمیز و تغییر آن به مسیر مورد نظر
        if self.success_url == 'home':
            return reverse_lazy(self.success_url)
        return self.success_url

    def get(self, request, *args, **kwargs):
        form = AuthenticationForm()
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('coffe:home')
            else:
                form.add_error(None, 'نام کاربری یا رمز عبور اشتباه است.')
        return render(request, self.template_name, {'form': form})


class MyLogoutView(LogoutView):
    def get_next_page(self):
        return 'coffe/homepage'

    def dispatch(self, request, *args, **kwargs):
        response = super().dispatch(request, *args, **kwargs)
        request.session.clear()
        return response


class CustomerListView(ListView):
    model = MyUser
    fields = '__all__'
    context_object_name = 'customers'

    # def get_queryset()
    def get_queryset(self):
        # original qs
        qs = super().get_queryset()
        # filter by a variable captured from url, for example
        return qs.filter(is_customer=True)

class CategoryListView(ListView):
    model = Category
    template_name = "coffe/category_list.html"
    context_object_name = "categories"

class CategoryCreateView(CreateView):
    model = Category
    fields = "__all__"
    template_name = "coffe/create_category.html"

class CategoryDeleteView(DeleteView):
    model = Category
    success_url = reverse_lazy("categories_list")

class CategoryUpdateView(UpdateView, ):
    model = Category
    fields = "__all__"
    success_url = reverse_lazy("categories_list")



class ItemListView(ListView):
    model = Item
    template_name = "coffe/itemـlist.html"
    context_object_name = "items"


class ItemCreateView(CreateView):
    model = Item
    fields = "__all__"
    template_name = "coffe/create_item.html"


class ItemUpdateView(UpdateView, ):
    model = Item
    fields = "__all__"
    success_url = "coffe:home"


class ItemDeleteView(DeleteView):
    models = Item
    success_url = reverse_lazy("coffe:home")


class AddToCartView(View):

    def post(self, request):
        item_id = request.POST.get('item_id')
        item = get_object_or_404(Item, pk=item_id)
        # Get the current cart from cookies or create a new empty cart
        cart = request.COOKIES.get('shopping_cart')
        cart = json.loads(cart) if cart else {}
        cart_item = cart.get(str(item.id), {'quantity': 0})
        cart_item['item_id'] = item.id
        cart_item['name'] = item.name
        cart_item['price'] = item.price
        cart_item['quantity'] += 1
        cart[str(item.id)] = cart_item
        response = redirect('/coffe/')
        response.set_cookie('shopping_cart', json.dumps(cart))
        messages.success(request, f'{item.name} added to the shopping cart!')
        return response


class RemoveFromCartView(View):

    def post(self, request):
        item_id = request.POST.get('item_id')
        item = get_object_or_404(Item, pk=item_id)
        cart = request.COOKIES.get('shopping_cart')
        cart = json.loads(cart) if cart else {}
        cart_item = cart.get(str(item.id), {'quantity': 0})
        cart_item['item_id'] = item.id
        cart_item['name'] = item.name
        cart_item['price'] = item.price
        if cart_item and cart_item['quantity'] > 0:
            cart_item['quantity'] -= 1
        cart[str(item.id)] = cart_item
        response = redirect('/coffe/')
        response.set_cookie('shopping_cart', json.dumps(cart))
        messages.success(request, f'{item.name} removed from shopping cart!')
        return response


class ViewShoppingCart(View):

    def get(self, request, *args, **kwargs):
        new_dic = {}
        cart = request.COOKIES.get('shopping_cart', '{}')
        cart = json.loads(cart)
        for value in cart.values():
            new_dic['name'] = value['name']
            new_dic['price'] = value['price']
            new_dic['quantity'] = value['quantity']
        print(new_dic)

        return render(request, 'coffe/order_list.html', context=new_dic)






class show_home(ListView):
    model = Item
    template_name = "coffe/homepage.html"
    context_object_name = "items"


class OrderListView(View):
    template_name = 'coffe/order_list.html'

    def get(self, request, *args, **kwargs):
        order = CustomerOrder.objects.all()
        return render(request, self.template_name, {"orders": order})

coffe/templates/coffe/cart.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

coffe/templates/coffe/category_list.html
{% extends 'base.html' %}

{% load static %}

{% block extraCSS%}
  <link rel="stylesheet" href="{% static 'coffe/css/style.css' %}" type="text/css">
{% endblock %}

{% block content %}
    <div id="intro" class="bg-image shadow-5-strong">
{#        <div class="container mt-3"#}
{#            {% block main %}#}
{#            {% include "coffe/item_list.html" %}#}
{#            {% endblock %}#}
{#        </div>#}
    </div>
{% endblock %}

coffe/templates/coffe/checkout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

coffe/templates/coffe/customer_create.html
{% extends 'base.html' %}

{% block main %}
    <div>
    <form method="post" action="{% url 'coffe:login' %}?next={{ request.GET.next }}">
        {% csrf_token %}
        <p>نام: {{ form.first_name }}</p>
        <p> نام خانوادگی: {{ form.last_name }}</p>
        <p> جنسیت: {{ form.gender}} </p>
        <p> نشانی پست الکترونیکی: {{ form.email}}</p>
        <p> شماره تلفن همراه: {{ form.phone }}</p>
        <p> نام کاربری: {{ form.username }}</p>
        <p> رمز وزود: {{ form.password }}</p>
        <p> آدرس: {{ form.address }}</p>

       <a href="{% url 'coffe:signup_user' %}"><button type="submit" class="btn btn-success">ثبت</button></a>
    </form>
    </div>
{% endblock  %}

coffe/templates/coffe/customer_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<!--    custmoers.first_name-->
<!--object_list-->
</body>
</html>

coffe/templates/coffe/homepage.html
{% extends 'base.html' %}

{% load static %}

{% block extraCSS%}
  <link rel="stylesheet" href="{% static 'tasks/css/style.css' %}" type="text/css">
{% endblock %}

{% block content %}
    <div id="intro" class="bg-image shadow-2-strong">
      <div class="mask" style="background-color: rgba(0, 0, 0, 0.8);">
        <div class="container d-flex align-items-center justify-content-center text-center h-100">
          <div class="text-white">
            <a class="btn btn-outline-light btn-lg m-2" href="" role="button"
              rel="nofollow" target="_blank">منو</a>
            <a class="btn btn-outline-light btn-lg m-2" href="" target="_blank"
              role="button">سبد خرید</a>
          </div>
        </div>
      </div>
    </div>
{% endblock %}

{% block main %}
{% include "coffe/item_list.html" %}
{% endblock %}

coffe/templates/coffe/item_list.html
<!-- list_item -->
<style>
    .spinner-border {
        margin-top: 120px;
        margin-left: 140px;
        margin-right: 140px;
        margin-bottom: 120px;
    }
</style>

<div class="container text-center">
    <div class="row">
        {% for item in items %}
            <div class="col-3">
                <div class="card" id="loading-card-{{ item.id }}">
                    <div class="spinner-border" role="status">
                        <span class="visually-hidden">Loading...</span>
                    </div>
                    <div class="card-body">
                        <h5 class="card-title placeholder-glow">
                            <span class="placeholder col-6"></span>
                        </h5>
                        <p class="card-text placeholder-glow">
                            <span class="placeholder col-4"></span>
                            <span class="placeholder col-6"></span>


                        </p>
                        <a class="btn btn-primary disabled placeholder col-6" aria-disabled="true"></a>
                    </div>
                </div>

                <div class="card" id="item-card-{{ item.id }}" style="display: none;">
                    <img src="{{ item.image.url }}" class="card-img-top" alt="..." height="300" width="150">
                    <div class="card-body">
                        <h5 class="card-title">{{ item.name }}</h5>
                        <p class="card-text">{{ item.category }} - قیمت: {{ item.price|floatformat:"0" }}</p>


                        <form method="post" action="{% url "coffe:add_to_cart" %}">
                            {% csrf_token %}
                            <input type="hidden" name="item_id" value="{{ item.id }}">
                            <button type="submit" class="btn btn-success">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16"
                                    fill="currentColor"
                                    class="bi bi-cart-plus-fill" viewBox="0 0 16 16">
                                    <path d="M.5 1a.5.5 0 0 0 0 1h1.11l.401 1.607 1.498 7.985A.5.5 0 0 0 4 12h1a2 2 0 1 0 0 4 2 2 0 0 0 0-4h7a2 2 0 1 0 0 4 2 2 0 0 0 0-4h1a.5.5 0 0 0 .491-.408l1.5-8A.5.5 0 0 0 14.5 3H2.89l-.405-1.621A.5.5 0 0 0 2 1zM6 14a1 1 0 1 1-2 0 1 1 0 0 1 2 0m7 0a1 1 0 1 1-2 0 1 1 0 0 1 2 0M9 5.5V7h1.5a.5.5 0 0 1 0 1H9v1.5a.5.5 0 0 1-1 0V8H6.5a.5.5 0 0 1 0-1H8V5.5a.5.5 0 0 1 1 0"></path>
                                </svg>
                            </button>
                        </form>

                         <form method="post" action="{% url "coffe:remove_from_cart" %}" >
                             {% csrf_token %}
                             <input type="hidden" name="item_id" value="{{ item.id }}">
                             <button type="submit" class="btn btn-outline-danger">
                                 <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16"
                                      fill="currentColor"
                                      class="bi bi-cart-dash-fill" viewBox="0 0 16 16">
                                     <path d="M.5 1a.5.5 0 0 0 0 1h1.11l.401 1.607 1.498 7.985A.5.5 0 0 0 4 12h1a2 2 0 1 0 0 4 2 2 0 0 0 0-4h7a2 2 0 1 0 0 4 2 2 0 0 0 0-4h1a.5.5 0 0 0 .491-.408l1.5-8A.5.5 0 0 0 14.5 3H2.89l-.405-1.621A.5.5 0 0 0 2 1zM6 14a1 1 0 1 1-2 0 1 1 0 0 1 2 0m7 0a1 1 0 1 1-2 0 1 1 0 0 1 2 0M6.5 7h4a.5.5 0 0 1 0 1h-4a.5.5 0 0 1 0-1"></path>
                                 </svg>
                             </button>
                         </form>
                    </div>

                </div>
            </div>
        {% endfor %}
    </div>
</div>
<script>
    {% load static %}
    setTimeout(function () {
        {% for item in items %}
            // Hide loading card and show main card content
            var loadingCard{{ item.id }} = document.getElementById("loading-card-{{ item.id }}");
            var itemCard{{ item.id }} = document.getElementById("item-card-{{ item.id }}");

            loadingCard{{ item.id }}.style.display = "none";
            itemCard{{ item.id }}.style.display = "block";
        {% endfor %}
    }, 150);
</script>
<!-- end_list_item -->

coffe/templates/coffe/login.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>loging</title>
    </head>
    <body>
        <form method="post" action="{% url 'coffe:login' %}">
            {% csrf_token %}
            {{ form.as_p }}
            {{ form.error_message }}
            <button type="submit">Login</button>
        </form>
    </body>
</html>

coffe/templates/coffe/menu.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

coffe/templates/coffe/order_list.html
{% extends 'base.html' %}

{% block main %}

    {% for item in new_dic %}
        {{ item }}

{#       <p> {{ item.name }} </p>#}
{#       <p> {{ item.price }} </p>#}
{#       <p> {{ item.quantity }} </p>#}

    {% endfor %}

{% endblock %}

coffe/templates/coffe/staff_panel.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>